Appsrn 332 desarrollo de package app tracking time
janis-commerce/app-tracking-time pull request #2
Opened 2024-09-13 20:43 UTC by GonzaFran

TICKET: https://janiscommerce.atlassian.net/browse/APPSRN-330

SUBTAREA: https://janiscommerce.atlassian.net/browse/APPSRN-332

**DESCRIPCIÓN DEL REQUERIMIENTO:**

**CONTEXTO:**

Actualmente, y en base a los últimos desarrollos trabajados y propuestos, nos dimos cuenta que necesitamos contar con una herramienta que nos permita y facilite hacer un seguimiento del tiempo que transcurre mientras que el usuario realiza alguna operación con cualquiera de las aplicaciones hasta que la termina.

No contar con este recurso nos impide, entre otras cosas:

-Conocer el tiempo que demora un usuario en completar una sesión de picking.

-Saber cuánto tardó un driver en completar una entrega.

-Reconocer cuánto demora un picker en conseguir y preparar cada producto de la sesión.

**REQUERIMIENTO:**

Para poder llevar un registro de tiempo de cada acción dentro de la app, necesitamos contar con un package que cumpla esta función de registro y que nos de herramientas para trabajar con los datos acumulados.

De esta manera, podremos conocer el tiempo operativo de cada acción, además de poder darle un uso a la información recabada que beneficie y agilice las operaciones del cliente.

**DESCRIPCIÓN DE LA SOLUCIÓN:**

Se armó la clase EvenTracker, que se encarga de proveer métodos para gestionar el almacenamiento de eventos asociados a un id en la base de datos. Estos eventos son objetos con un formato:

```sh
{
 id: string,
 time: new Date().toISOString(),
 type: 'start' | 'pause' | 'resume' | 'finish',
 payload: {}
}
```

Para el almacenamiento en la base de datos se usó realm, que se encarga de crear un archivo dónde almacenar la información de los eventos y también provee métodos para guardar, buscar y eliminar uno o todos los elementos de la base de datos.

También se agregaron validaciones que permiten o evitan agregar determinado tipo de eventos dependiendo del último tipo de evento añadido para el id que se busca guardar. (revisar anailisis funcional del ticket).

Cada método de la clase EventTracker cuenta con su jsdoc para entender su funcionamiento  y la mayoría de ellos retornan promesas debido a que interactuan con la base de datos.

La clase cuenta con 2 métodos relacionados a la escucha de eventos de cambio de estado de la aplicación, que se encargan añadir un listener para pausar TODOS los ids posibles cuando la app pasa a segundo plano, y también para remover el listener una vez que la app deja de estar activa. 

**¿CÓMO PROBARLO?**

Para probarlo se necesita vincular el package con yalc y luego instanciar la clase EventTracker dentro del repo de la app.
La clase espera un string como argumento que va a usarse como nombre del archivo .realm que se va a generar y que va a encargarse de almacenar todos los registros ingresados.

Para añadir un evento se debe usar el método addEvent:

```sh
 const addEvent = async () => {
  const [response, error] = await EventTracker.addEvent({id:'123', type:'start'})
}
```

Para obtener todos los eventos relacionados a un id se usa getEventsById:

```sh
 const addEvent = async () => {
  const [response, error] = await EventTracker.getEventsById('123')

 console.log(response)
}
```

para borar todos los eventos asociados a un id:

```sh
 const addEvent = async () => {
  const [response, error] = await EventTracker.deleteEventsById('123')

}
```

Y así con la mayoría de eventos.

Para agregar la detección del cambio de estado de la app y así pausar todos los ids que se encuentren en curso, y no estén pausados o finalizados, es necesario llamar, en el app.js un useEffect de la siguiente manera:

```sh

import EventTracker from 'src/utils/eventrackerclass';

const App = () => {
	//...
	useEffect(() => {
		// Iniciar el listener cuando el componente se monta
		EventTracker.startListening();
	
		// Eliminar el listener cuando el componente se desmonta
		return () => {
		  EventTracker.stopListening();
		};
	  }, []); 

```

De esta manera, siempre que la app pase a segundo plano o sea cerrada, el package intentará pausar todos los ids posibles.

2024-09-17 19:09 UTC, pablodamianberdun requested changes

2024-09-17 19:09 UTC, pablodamianberdun commented on README.md
> +```
@GonzaFran Podemos agregar ejemplos de uso en el Readme

2024-09-17 19:09 UTC, pablodamianberdun commented on lib/event-tracker-error.js
> +export default EventTrackerError;
@GonzaFran Para que utilizas esta clase? Que ventaja nos da trabajar el error en una clase aparte ?

2024-09-17 19:09 UTC, pablodamianberdun commented on lib/database.js
> +            await this._validateFolderCreation();
@GonzaFran Esta funcion podemos ejecutarla solo una vez en el constructor. Y te ahorras ejecutarla cada vez que se llama un metodo de la DB

2024-09-17 19:09 UTC, pablodamianberdun commented on lib/event-tracker.js
> +        } catch (error) {
@GonzaFran Tenemos que unificar lo que retornamos en ambos metodos que agregan eventos
En addEvent retornas solo time
En addManyEvents retornas {id, time}

Podemos retornar en ambos {id, time}, siendo en addManyEvents un array

2024-09-17 19:09 UTC, pablodamianberdun commented on lib/event-tracker.js
> +    }
@GonzaFran Este metodo se podrá usar desde la app.

Si no se podrá, agregar el prefijo _
Si se puede, estamos limitando a tener solo el tipo, si fuese getLastEventById, podemos acceder a toda la info que nos llegue a findedEvent

2024-09-17 19:09 UTC, pablodamianberdun commented on lib/event-tracker.js
> +    async isEventAlreadyStarted (id) {
@GonzaFran Este metodo no es privado ?

2024-09-17 19:09 UTC, pablodamianberdun commented on lib/event-tracker.js
> +    async stopEventsInBackground () {
@GonzaFran Este metodo no es privado ?

2024-09-17 19:09 UTC, pablodamianberdun commented on lib/event-tracker.js
> +    async handleAppStateChange(nextAppState) {
@GonzaFran Este metodo no es privado ?

2024-09-17 19:09 UTC, pablodamianberdun commented on db/schemas/eventSchema.js
> +            payload: {type: 'mixed'}
@GonzaFran que ventajas nos da usar 'mixed' en vez de usar 'string' y hacer siempre un JSON.parse(payload) ??

2024-09-17 19:12 UTC, pablodamianberdun requested changes
@GonzaFran  te deje varios comentarios

2024-09-17 19:32 UTC, GonzaFran commented on lib/event-tracker-error.js
> +export default EventTrackerError;
@pablodamianberdun tomé de referencia lo que hizo back en su pkg de [micro-service call](https://github.com/janis-commerce/microservice-call/blob/master/lib/microservice-call-error.js) donde, además de retornarle el error, les da más contexto sobre lo que pasó. Pensé en copiar su idea para que, en caso de que lo necesitemos más adelante, nosotros también podamos contar con errores más completos. 
Hoy no tiene más utilidad que, si querés, manejar el error.

2024-09-17 19:58 UTC, GonzaFran commented on db/schemas/eventSchema.js
> +            payload: {type: 'mixed'}
@pablodamianberdun ninguna creo yo, me quedó viejo el tipo. Ahora hago el cambio.

2024-09-17 20:02 UTC, GonzaFran commented on lib/event-tracker.js
> +    async isEventAlreadyStarted (id) {
@pablodamianberdun no, este lo voy a usar, por ejemplo, en el inicio de una sesión para validar si el evento ya fue trackeado previamente y, en todo caso, guardar un evento de "resume", caso contrario guardar uno de "start"

2024-09-17 20:06 UTC, GonzaFran commented on lib/event-tracker.js
> +    }
@pablodamianberdun si, se va a poder usar, lo limité a que me devuelva sólo el tipo porque el resto de datos no los veo relevantes del lado de la app: 
- el id ya lo tengo.
- el tiempo invidualmente no me sirve así que no le veía uso.
- el payload tuve mis dudas pero no pensé usarlo para nada invidualmente. (Hoy tampoco sé qué es lo que cargaríamos en el payload que necesite y no tenga en la app).

En todo caso hago el ajuste para que sea más flexible.

2024-09-18 14:02 UTC, GonzaFran commented on lib/database.js
> +            await this._validateFolderCreation();
@pablodamianberdun ya hice el cambio, se ejecuta en el constructor.

2024-09-18 15:15 UTC, pablodamianberdun requested changes

2024-09-18 15:15 UTC, pablodamianberdun commented on lib/event-tracker.js
> +            return findedEvent;
@GonzaFran aca no falta parsear el evento ?

con Event.parseEventFromDB

2024-09-18 16:41 UTC, pablodamianberdun approved these changes

2024-09-19 14:45 UTC, merged