updated getElapsedTime params
janis-commerce/app-tracking-time pull request #7
Opened 2024-11-27 13:58 UTC by GonzaFran

LINK DE TAREA:
https://janiscommerce.atlassian.net/browse/JPRN-1987

LINK DE SUBTAREA:
https://janiscommerce.atlassian.net/browse/JPRN-1994

CONTEXTO:

Actualmente, la app de picking está utilizando un contador de tiempo en el header que refleja, en hh:mm:ss, la cantidad de tiempo que pasó entre el inicio del picking y la hora actual. 
Sin embargo, un evolutivo de este desarrollo es poder mostrar un contador regresivo que le muestre al picker cuánto tiempo tiene disponible para pickear. Para hacer esto, back está enviando dentro de cada ronda los datos `estimatedPickingTime` y `estimatedpickingRemainingTime` que indican el tiempo total para pickear y el tiempo disponible para pickear respectivamente.
Estos valores están representados en milisegundos, por lo que, para poder calcular cuánto tiempo le queda al picker, tenemos que restar el tiempo transcurrido de estos valores.

Hoy el package tiene el método `getElapsedTIme`, que devuelve el tiempo transcurrido entre 2 fechas, pero lo hace en formato dd:hh:mm:ss. Esto es un problema ya que, para poder hacer el calculo entre los valores que envía back y el tiempo que hay que restar, tendríamos que obtener el tiempo transcurrido y hacer un calculo posterior para pasarlo a milisegundos.

NECESIDAD:
Ya que necesitamos el método `getElapsedTIme` para conocer el tiempo transcurrido, propongo adaptar sus parametros para que pueda recibir un 3er valor que indique si queremos que el valor que devuelva sea en el formato actual o en milisegundos.

DESCRIPCIÓN DE LA SOLUCIÓN:

Se adaptó `getElapsedTime` para que pueda recibir un objeto como argumento, y que este objeto contenga los valores:
- `startTime`, hora de inciio obligatoria
- `finishTime`, hora de finalización opcional (se toma la hora actual en caso de que no esté)
- `formatted`, por defecto su valor es `true`, por lo que siempre devolverá el valor formateado a menos que se declare lo contrario.

Este cambio permite que el dato obtenido sea más flexible y utilizable en varias situaciones.

2025-04-01 19:39 UTC, pablodamianberdun requested changes

2025-04-01 19:39 UTC, pablodamianberdun commented on lib/event-tracker.js
> +            if(currentEvent.type !== 'pause') return time;
@GonzaFran el primer param podemos renombrarlo a totalPausedTime, queda mas claro

2025-04-01 19:39 UTC, pablodamianberdun commented on lib/event-tracker.js
> +            return time;
@GonzaFran directamente retorna totalPausedTime + timeDifference.
En la misma linea donde retornas, hace la suma

2025-04-01 19:39 UTC, pablodamianberdun commented on lib/event-tracker.js
> +            if(!Object.keys(nextEvent).length) {
@GonzaFran mejorar la condicion

nextEvent.type !== 'resume' || nextEvent.type !== 'finish'

2025-04-01 21:42 UTC, GonzaFran commented on lib/event-tracker.js
> +            if(!Object.keys(nextEvent).length) {
@pablodamianberdun al final, lo ajusté pero para que la condición que se tiene que cumplir sea esta:

nextEvent.type !== 'resume' && nextEvent.type !== 'finish"

2025-04-03 18:42 UTC, pablodamianberdun approved these changes

2025-04-03 18:56 UTC, merged